version: "3.8"
services:
  postgres:
   image: postgres
   ports:
    - "5433:5432"
   environment:
    POSTGRES_USER: postgres
    POSTGRES_DB: review
    POSTGRES_PASSWORD: 123456
  redis:
    image: redis
    ports:
      - "6379:6379"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: review
      POSTGRES_PASSWORD: 123456
